### ISSUE TITLE
Practica Prototipo en Figma

### ISSUE THREAD

**Issue by Luz1727** [SistemasTecTlaxiaco/actividad-1-practicaprototipo-equipo-topic-avanza4usssss#2]
[PRACTICA 1_REPORTE FIGMA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-practicaprototipo-equipo-topic-avanza4usssss/files/10752946/PRACTICA.1_REPORTE.FIGMA.pdf)

**Comment by yanet02** [comment]
Portada (25 puntos) BIEN HECHO.
-Procedimiento (22 puntos) Faltó agregar descripción de material.
-Figuras, ilustraciones y fotografías ( 20 puntos)Faltaron más figuras de la práctica..
Resultados y conclusiones: (25 puntos) Bien hecho.
Total : 92 de 100.
Calificación: 18.4 % de 20%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
